### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by yar0d** [rwatts3/atom-ide-vue#3]
Just open a .vue file

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: "Arch Linux"
**Thrown From**: [ide-vue](https://github.com/rwatts3/atom-ide-vue) package 0.1.3

### Stack Trace

Uncaught Error: Connection is closed.

```
At /home/daniel/.atom/packages/ide-vue/node_modules/vscode-jsonrpc/lib/main.js:604

Error: Connection is closed.
    at /packages/ide-vue/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/packages/ide-vue/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/packages/ide-vue/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/packages/ide-vue/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didCloseTextDocument (/packages/ide-vue/node_modules/atom-languageclient/build/lib/languageclient.js:128:10)
    at TextEditorSyncAdapter.didClose (/packages/ide-vue/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:266:22)
    at wrapped (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom-beta/resources/app/src/text-editor.js:661:26)
    at TextEditor.module.exports.Model.destroy (/usr/share/atom-beta/resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom-beta/resources/app/src/pane.js:708:24)
    at TabBarView.module.exports.TabBarView.closeTab (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/usr/share/atom-beta/resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
     -1:28.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:27.9.0 core:move-left (input.hidden-input)
     -1:27.6.0 intentions:highlight (input.hidden-input)
  8x -1:27.6.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:25.1.0 editor:select-to-end-of-word (input.hidden-input)
     -1:24.1.0 core:select-right (input.hidden-input)
     -1:23.5.0 intentions:highlight (input.hidden-input)
     -1:23.2.0 core:cut (input.hidden-input)
     -1:22.2.0 atom-save-all:saveAll (input.hidden-input)
  5x -1:14.5.0 core:move-down (input.hidden-input)
     -1:13.5.0 core:move-up (input.hidden-input)
     -1:13.1.0 intentions:highlight (input.hidden-input)
     -1:12.7.0 editor:toggle-line-comments (input.hidden-input)
     -1:11.7.0 atom-save-all:saveAll (input.hidden-input)
  2x -0:18.7.0 editor:move-to-first-character-of-line (input.hidden-input)
  3x -0:18.3.0 core:select-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-ide-ui 0.3.3 
atom-save-all 0.4.1 
autoclose-html 0.23.0 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.11 
git-control 0.9.0 
git-plus 7.9.3 
go-debug 1.5.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-vue 0.1.3 
intentions 1.1.5 
language-ejs 0.4.0 
language-pug 0.0.21 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.3.2 
linter-golinter 1.2.2 
linter-js-standard 4.0.2 
linter-jshint 3.1.5 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-ui-default 1.6.10 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
monokai 0.24.0 
pigments 0.40.2 
split-diff 1.5.1 
standard-formatter 2.8.0 
tree-view-git-status 1.4.0 
```

**Comment by dexif** [comment]
In atom 1.21.0 beta1 too...
